version: '3.8'

services:

  timescaledb:
    image: timescale/timescaledb:2.0.0-pg12
    restart: always
    environment:
      POSTGRES_PASSWORD: supersecurepassword
      POSTGRES_DB: wiki

    ports:
      - "${MY_DOCKER_IP:-127.0.0.1}:5432:5432"

  user-statistic-service:
    depends_on:
      - "timescaledb"
    build:
      context: ./user-statistic-service
      dockerfile: Dockerfile
    ports:
      - "${MY_DOCKER_IP:-127.0.0.1}:8000:8000"

    command: >
      /bin/bash -c "
        while ! nc -z wiki_analyzer_python_timescaledb_1 5432;
        do
          echo sleeping;
          sleep 1;
        done;
        python3 -m app.main
        echo Connected!;
      "


  streaming-service:
    depends_on:
      - "timescaledb"
    build:
      context: ./streaming-service
      dockerfile: Dockerfile
    ports:
      - "${MY_DOCKER_IP:-127.0.0.1}:8001:8000"

    command: >
      /bin/bash -c "
        while ! nc -z wiki_analyzer_python_timescaledb_1 5432;
        do
          echo sleeping;
          sleep 1;
        done;
        python3 -m app.main
        echo Connected!;
      "

  mongodb:
    image: mongo:4.0.8
    restart: unless-stopped
    command: --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: qwerty
      MONGO_INITDB_DATABASE: wiki_analyzer
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - mongodbdata:/data/db
    ports:
      - "27020:27017"

  timeseries-service:
    depends_on:
      - "mongodb"
    build:
      context: ./timeseries-service
      dockerfile: Dockerfile
    environment:
      ENV: docker
    ports:
      - "${MY_DOCKER_IP:-127.0.0.1}:8003:8000"


volumes:
  mongodbdata:
    driver: local